### PR TITLE
Food Menu

### PR DESCRIPTION
**Pull request by errea**
# Description
* Create food menu component
* Create content for food menu
* Create and fix link part from menu button on the home page
* Adjust image to full scale

### CODE REVIEW

**Review by david-lafontant — CHANGES_REQUESTED** [review]
Hello @errea ,
You did a great job, however, the menu is not displayed, so please fix it.
menu-screenshot

**Comment by errea** [comment]
@david-lafontant, this has been fixed

**Review by david-lafontant — APPROVED** [review]

**Review by david-lafontant — APPROVED** [review]
@errea @hs-eri-ngozi-okereafor You made a good job.
It's time to merge!

**Comment by errea** [comment]
Thank you @david-lafontant  for approving he changes 
Next steps !!!

**Pull request merged**
